// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swqmwffzujskohbdguml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3cW13ZmZ6dWpza29oYmRndW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjM0MTEsImV4cCI6MjA2NzUzOTQxMX0.4_1J7zQfOGnR3RLCDlZS_Xzx4GRiqbYd7NZdXRtQlD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});